version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      nextjs:
        patterns:
          - "next"
          - "@next/*"
      shadcn:
        patterns:
          - "@radix-ui/*"
          - "class-variance-authority"
          - "tailwind-merge"
          - "tailwindcss-animate"
      testing:
        patterns:
          - "@testing-library/*"
          - "jest"
          - "jest-*"
    ignore:
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"