import { useState, useRef, useEffect } from "react";
import { Send, Settings, MessageSquare, User, Bot } from "lucide-react";
import MessageBubble from "./MessageBubble";
import PDFUpload from "./PDFUpload";
import TopicSelector from "./TopicSelector";
import { Message } from "@/types";

const topics = [
  "AI-generated child pornography",
  "Abandoning or endangering",
  "Abuse of corpse offenses",
  "Abuse of office definitions",
  "Acceptance of honorarium",
  "Access device tampering",
  "Accomplice witness testimony",
  "Adequate cause definition",
  "Adjudicatory proceeding",
  "Adjudicatory proceedings",
  "Adult stem cells",
  "Adulterated goods standards",
  "Advertising by professionals",
  "Affirmative defense",
  "Affirmative defense criteria",
  "Affirmative defense for minors",
  "Affirmative defense in prosecution",
  "Affirmative defense notifications",
  "Affirmative defenses",
  "Affirmative defenses for firearm access",
  "Affirmative defenses for judicial and law enforcement officers",
  "Affirmative defenses for possession offenses",
  "Affirmative findings under Article 42.0197",
  "Age Restrictions on Firearms",
  "Age and criminal history limitations",
  "Age-related offense rules",
  "Agent conduct and corporate liability",
  "Agent definitions",
  "Aggravated Perjury",
  "Aggravated Sexual Assault",
  "Aggravated assault",
  "Aggravated kidnapping",
  "Aggravated perjury defenses",
  "Aggravated promotion of prostitution",
  "Aggravated robbery",
  "Aggravated sexual assault",
  "Aggregation of offenses",
  "Aiding suicide offense",
  "Airports",
  "Alcohol concentration levels",
  "Alcohol concentration measurement",
  "Alcohol possession laws",
  "Alcoholic beverage",
  "Alcoholic beverage permits",
  "Alternative fine provisions",
  "Amendments",
  "American vessel documentation",
  "Amusement park definition",
  "Animal abuse laws",
  "Animal abuse penalties",
  "Animal and livestock protection",
  "Animal attack offenses",
  "Animal cruelty offenses",
  "Animal custody and care",
  "Animal neglect and abandonment",
  "Animal sexual contact",
  "Appropriation of property",
  "Arson",
  "Arson offenses",
  "Artificially generated media",
  "Assault on public servants",
  "Assaultive offenses",
  "Assistance animal",
  "Assisted reproduction",
  "Assisted reproduction definitions",
  "Attorney General assistance",
  "Attorney General prosecution jurisdiction",
  "Attorney general coordination",
  "Attorney general jurisdiction",
  "Automated teller machine",
  "Automated teller machines",
  "Bail jumping",
  "Barratry offenses",
  "Bestiality offense",
  "Bias or prejudice offenses",
  "Bias-motivated offenses",
  "Bigamy statute",
  "Bill Enactments",
  "Bill Numbers",
  "Boating while intoxicated",
  "Boating with child passenger intoxication",
  "Bodily injury",
  "Bookmaking activities",
  "Bribery offense",
  "Burglary definitions",
  "Burglary offense elements",
  "Business entities",
  "Capital felonies",
  "Capital felony punishment",
  "Capital felony punishments",
  "Capital murder",
  "Cardholder definition",
  "Caregiver and coach influence",
  "Catalytic converter",
  "Cellular telephone components",
  "Child Pornography",
  "Child age criteria",
  "Child and Disabled Individual Trafficking",
  "Child custody determination",
  "Child custody escape",
  "Child custody interference",
  "Child definition",
  "Child endangerment offense",
  "Child firearm discharge",
  "Child labor laws",
  "Child pornography laws",
  "Child protection",
  "Child protection laws",
  "Child recruitment offenses",
  "Child sexual conduct depictions",
  "Child support obligations",
  "Child trafficking",
  "Child visual material offenses",
  "Child-care facility employee offenses",
  "Child-related obscene material penalties",
  "Civil commitment facilities",
  "Civil commitment facility",
  "Civil remedies",
  "Claims payment process",
  "Class A Misdemeanor",
  "Class A misdemeanor",
  "Class A misdemeanor and felony penalties",
  "Class A misdemeanor offense",
  "Class A misdemeanor offenses",
  "Class A misdemeanor penalties",
  "Class A misdemeanor violations",
  "Class A misdemeanors",
  "Class B misdemeanor",
  "Class B misdemeanor offense",
  "Class B misdemeanor offenses",
  "Class B misdemeanor penalties",
  "Class C misdemeanor",
  "Class C misdemeanor penalties",
  "Classification of offenses",
  "Classification of offenses and penalties",
  "Classification of railroad-related offenses",
  "Clergyman professional conduct",
  "Cockfighting offense",
  "Code of Criminal Procedure",
  "Coercion",
  "Coercion in gang membership",
  "Coercion in trafficking",
  "Combination in criminal activities",
  "Commercial bribery definitions",
  "Commercial social networking site",
  "Communication common carrier",
  "Communication common carrier regulations",
  "Communication device regulations in correctional settings",
  "Communication restrictions",
  "Community standards for obscenity",
  "Community supervision officers",
  "Compelling Prostitution",
  "Computer crimes definitions",
  "Computer definitions",
  "Computer network",
  "Computer network offenses",
  "Computer virus",
  "Computer-generated child images",
  "Concealed handgun laws",
  "Concurrent Jurisdiction",
  "Conditions of bond",
  "Condominium and tenant defenses",
  "Condominium handgun defenses",
  "Consent",
  "Consent and privacy",
  "Consent as defense to assault",
  "Consent defense",
  "Consent for camping",
  "Consent in assisted reproduction",
  "Consent in media production",
  "Consent requirements",
  "Conspiracy to commit offenses",
  "Consumer product definition",
  "Consumer protection laws",
  "Continuing course of conduct aggregation",
  "Continuous Trafficking of Persons",
  "Continuous family violence",
  "Continuous promotion of prostitution",
  "Continuous sexual abuse",
  "Continuous smuggling of persons",
  "Controlled substance",
  "Controlled substance delivery",
  "Controlled substance manufacturing",
  "Controlled substance offenses",
  "Controlled substance penalty enhancements",
  "Controlled substances",
  "Conviction criteria",
  "Conviction definitions",
  "Copper or brass material",
  "Corporate and association punishments",
  "Corporate criminal liability",
  "Corporations and business entities",
  "Correctional facilities",
  "Correctional facility definitions",
  "Correctional facility guards and peace officers",
  "Correctional facility offenses",
  "Correctional facility regulations",
  "Correctional facility security",
  "Counterfeit Mark Definition",
  "Counterfeit gift cards",
  "Counterfeit telecommunications devices",
  "Court Order Violations",
  "Court sentencing guidelines",
  "Credit card abuse",
  "Criminal Offense",
  "Criminal Offenses and Penalties",
  "Criminal Offenses and Prosecution",
  "Criminal Penalties",
  "Criminal Procedure",
  "Criminal Responsibility",
  "Criminal activity classification",
  "Criminal charges",
  "Criminal conspiracy penalties",
  "Criminal convictions",
  "Criminal instruments",
  "Criminal investigation procedures",
  "Criminal law terms",
  "Criminal liability",
  "Criminal mischief",
  "Criminal misdemeanor offenses",
  "Criminal negligence",
  "Criminal negligence in firearm security",
  "Criminal nonsupport",
  "Criminal offense classification",
  "Criminal offense definitions",
  "Criminal offense prevention",
  "Criminal offense punishment categories",
  "Criminal offense reporting requirements",
  "Criminal offenses",
  "Criminal offenses and intent",
  "Criminal offenses and penalties",
  "Criminal penalties",
  "Criminal penalties for data tampering",
  "Criminal procedure",
  "Criminal procedure amendments",
  "Criminal prosecution classifications",
  "Criminal responsibility",
  "Criminal responsibility of business entities",
  "Criminal solicitation",
  "Criminal solicitation of a minor",
  "Criminal street gang firearm offenses",
  "Criminal street gangs",
  "Criminally negligent homicide",
  "Critical infrastructure facilities",
  "Critical infrastructure facility",
  "Critical infrastructure offenses",
  "Cruelty to nonlivestock animals",
  "Currency definitions",
  "Custodial rights violations",
  "Custody and detention",
  "Cyber attack definition",
  "Damaging critical infrastructure",
  "Data definition and storage",
  "Deadly conduct offense",
  "Deadly force justification",
  "Deadly weapon use",
  "Deadly weapon use in felonies",
  "Deadly weapons",
  "Death penalty provisions",
  "Debit card abuse",
  "Deception in transactions",
  "Deceptive business practices",
  "Decryption and encrypted communications",
  "Deep fake media definition",
  "Defense to prosecution",
  "Defenses for law enforcement and school administrators",
  "Deferred Action for Childhood Arrivals",
  "Deferred adjudication community supervision",
  "Definition of emergency conditions",
  "Definition of harmful material",
  "Definition of property",
  "Definition of service",
  "Definition of sexual conduct",
  "Definitions in bribery and corrupt influence",
  "Definitions of animal-related terms",
  "Definitions of business terms",
  "Definitions of cockfighting terms",
  "Definitions of deliver and publish",
  "Definitions of emergency and utility",
  "Definitions of fiduciary roles",
  "Definitions of financial instruments",
  "Definitions of intimate areas",
  "Definitions of land types",
  "Definitions of legal terms in correctional context",
  "Definitions of marking devices",
  "Definitions of sexual conduct",
  "Definitions of sexual intercourse",
  "Definitions of sexual offenses",
  "Definitions of vulnerable individuals",
  "Depiction of a child",
  "Deportation offenses",
  "Destruction of flag",
  "Digital imprint",
  "Disability classifications",
  "Disability support animals",
  "Disabled individual",
  "Disabled individual abuse",
  "Disciplinary use of force on minors",
  "Disclosure of confidential information",
  "Disorderly conduct offenses",
  "Dissemination of personal information",
  "Dog fighting offense",
  "Dog-fighting equipment",
  "Driver's license display requirements",
  "Driving while intoxicated",
  "Driving with child passenger intoxication",
  "Drug dispensation and administration",
  "Duress defense",
  "Duty to report visual material",
  "Economic benefit",
  "Effect of Penal Code",
  "Effective Dates",
  "Effective consent",
  "Effective consent criteria",
  "Elderly age criteria",
  "Elderly individual",
  "Elderly individual definition",
  "Elderly individual protection",
  "Elderly protection",
  "Election Code contributions",
  "Election law",
  "Electric generating plant",
  "Electric utility",
  "Electric utility substation",
  "Electronic Transmission",
  "Electronic communication",
  "Electronic communication definition",
  "Electronic communication definitions",
  "Electronic communication offenses",
  "Electronic communication threats",
  "Electronic communications abuse",
  "Electronic communications device misuse",
  "Electronic communications service",
  "Electronic data tampering",
  "Electronic or mechanical tracking device",
  "Elements of offense",
  "Emergency call obstruction offense",
  "Emergency medical services personnel",
  "Emergency response offenses",
  "Emergency service interference",
  "Emergency services communication",
  "Emergency services personnel",
  "Emergency vehicle access",
  "Employee Offense",
  "Employee of a facility",
  "Employment Harmful to Children",
  "Employment harmful to children",
  "Employment in child-care facilities",
  "Encrypted private information",
  "Encrypted signal decoding",
  "Encryption service",
  "Enhanced offenses",
  "Enhanced penalties for elderly victims",
  "Enticing a child",
  "Escape definition",
  "Escape implements",
  "Escape offenses",
  "Exceptions for licensed agents",
  "Exclusions for travel discounts",
  "Exemptions for accredited institutions",
  "Exemptions for media dissemination",
  "Expired card definition",
  "Exploitation of emotional dependency",
  "Exploitation of vulnerable individuals",
  "Explosive and firearm classification",
  "Exposure to bodily fluids",
  "Extended power outage",
  "Failure to appear",
  "Failure to appear defenses",
  "Failure to identify offense",
  "Failure to notify and report deaths",
  "Failure to provide death notice",
  "Failure to report assault",
  "Failure to report death of prisoner",
  "Failure to report felony",
  "False Statements",
  "False advertising",
  "False documents",
  "False emergency reports",
  "False entries in government documents",
  "False identification as peace officer",
  "False identification to peace officer",
  "False or misleading statements",
  "False report of missing child",
  "False report to law enforcement",
  "False reports",
  "False reports to emergency services",
  "False representation as lawyer",
  "False statement offenses",
  "Family violence",
  "Family violence and trafficking shelter centers",
  "Family violence offenses",
  "Federal Communications Commission monitoring",
  "Federal cigarette regulations",
  "Federal firearm law enforcement",
  "Federal law enforcement officer",
  "Felony Classifications",
  "Felony Conviction Firearm Prohibition",
  "Felony Sentencing Guidelines",
  "Felony and misdemeanor classifications",
  "Felony and misdemeanor distinctions",
  "Felony authorization in corporations",
  "Felony barratry",
  "Felony classification",
  "Felony classification by benefit value",
  "Felony classification by sale amount",
  "Felony classification by value",
  "Felony classifications",
  "Felony classifications for trade secret theft",
  "Felony convictions",
  "Felony degree upgrades",
  "Felony degrees and defenses",
  "Felony fines",
  "Felony fines and imprisonment",
  "Felony firearm possession restrictions",
  "Felony imprisonment terms",
  "Felony offense classifications",
  "Felony offenses",
  "Felony offenses related to property damage",
  "Felony offenses under Section 22.04",
  "Felony reporting requirements",
  "Felony sentencing guidelines",
  "Fiduciary relationship breach",
  "Financial abuse",
  "Financial abuse of elderly",
  "Financial exploitation",
  "Financial instruments",
  "Financing Statement",
  "Financing barratry",
  "Fines for business entities",
  "Fire and explosion laws",
  "Firearm",
  "Firearm Sales Restrictions",
  "Firearm accessibility to children",
  "Firearm and stun gun definitions",
  "Firearm definitions",
  "Firearm discharge in municipalities",
  "Firearm discharge regulations",
  "Firearm possession after misdemeanor conviction",
  "Firearm possession by armed forces",
  "Firearm possession exceptions",
  "Firearm possession offenses",
  "Firearm regulation restrictions",
  "Firearm smuggling",
  "Firearm storage warning",
  "Firearms registration",
  "Firefighter definitions",
  "Fireworks offenses and penalties",
  "First Amendment speech protections",
  "First degree felony punishment",
  "First responder definition",
  "First responder definitions",
  "Fiscal agents",
  "Flag definition and exceptions",
  "Fleeing from law enforcement",
  "Flying while intoxicated",
  "Forced labor",
  "Foreign country custody laws",
  "Foreign government agents",
  "Foreign government entities",
  "Foreign terrorist organizations",
  "Forgery definition",
  "Forgery offenses",
  "Fraud aggregation",
  "Fraud and harm to victims",
  "Fraudulent Filing",
  "Fraudulent military records",
  "Fraudulent transfer",
  "Fugitive from justice penalties",
  "Gambling Definitions",
  "Gambling device restrictions",
  "Gambling promotion offenses",
  "Gang leadership activities",
  "General Provisions",
  "Gift card fraud",
  "Gift card redemption information",
  "Government Code Section 411.1884",
  "Government Code reporting",
  "Governmental function",
  "Governmental functions",
  "Governmental record definitions",
  "Governmental records",
  "Graffiti Offense",
  "Gratuity regulations",
  "Group home and care facility responsibilities",
  "Group home regulations",
  "Habitation and building",
  "Handgun carry licenses",
  "Handgun carry regulations",
  "Handgun carrying laws",
  "Handgun licensing law",
  "Handgun possession defense",
  "Handgun possession restrictions",
  "Harassment in correctional facilities",
  "Harassment of public servants",
  "Harboring runaway child",
  "Health and Safety Code",
  "Health care and mental health providers",
  "Health care claims",
  "Health care fraud",
  "Health care practitioners",
  "Health care program offenses",
  "Health care programs",
  "Health care services provider roles",
  "High managerial agent",
  "High managerial agent liability",
  "Hindering apprehension",
  "Hindering secured creditors",
  "Hoax bomb offenses",
  "Homosexual conduct statute",
  "Hospital personnel definitions",
  "House Bills",
  "Human Trafficking Offenses",
  "Human fetal tissue legal definitions",
  "Identifying information",
  "Identity theft offense",
  "Illegal divulgence of communications",
  "Illegal employment solicitation methods",
  "Illegal entry definitions",
  "Illegal entry from foreign nation",
  "Illegal reentry by certain aliens",
  "Immediate life-threatening situation",
  "Immigration detainer compliance",
  "Immigration law enforcement",
  "Immunity from prosecution",
  "Impersonating public servant",
  "Imprisonment for promoting child sexual material",
  "Improper contact with victim",
  "Improper influence",
  "Improper relationships in schools",
  "Improper sexual activity with committed person",
  "Improvised explosive device",
  "Incest laws",
  "Inconsistent statements in perjury",
  "Indecency with a child",
  "Indecent Assault",
  "Indecent assault",
  "Indecent exposure offense",
  "Injury or death during apprehension",
  "Injury or death during flight",
  "Injury to vulnerable individuals",
  "Institution of higher education",
  "Insufficient funds knowledge presumption",
  "Insurance claim restitution",
  "Insurance fraud offense",
  "Insurance policy definitions",
  "Intent to avoid payment",
  "Intent to defraud",
  "Intent to defraud or harm",
  "Intent to harm or defraud",
  "Interactive computer service",
  "Interception of communications",
  "Interference with emergency calls",
  "Interference with government radio frequencies",
  "Interference with guardian rights",
  "Internet definition",
  "Interstate firearm purchase",
  "Intimate area photography",
  "Intimate visual material",
  "Intoxicated operation",
  "Intoxication assault",
  "Intoxication defense",
  "Intoxication definitions",
  "Intoxication manslaughter",
  "Invasion of privacy",
  "Invasive visual recording",
  "Investigation and reporting of inmate deaths",
  "Investigational stem cell treatment",
  "Issuance of bad checks",
  "Judicial proceedings",
  "Jurisdiction recognition",
  "Jury Unanimity",
  "Jury unanimity",
  "Jury unanimity in criminal cases",
  "Jury unanimity in prosecution",
  "Jury unanimity requirements",
  "Justification for use of force",
  "Justification of conduct",
  "Juvenile detention facilities",
  "Juvenile facility operations",
  "Juvenile probation",
  "Keeping a gambling place",
  "Kidnapping definitions",
  "Kidnapping intent",
  "Kidnapping offense",
  "Law enforcement",
  "Law enforcement communication",
  "Law enforcement duties",
  "Law enforcement officer protection",
  "Law enforcement orders",
  "Law enforcement reporting",
  "Law enforcement responsibilities",
  "Law enforcement use of drones",
  "Lawful arrest",
  "Lease agreements",
  "Leaving child in vehicle",
  "Legal Amendments",
  "Legal Definitions",
  "Legal amendments",
  "Legal amendments and effective dates",
  "Legal amendments and statutes",
  "Legal amendments to penal code",
  "Legal amendments to video service device laws",
  "Legal authority in property transactions",
  "Legal authorization",
  "Legal communication exceptions",
  "Legal defenses",
  "Legal defenses and penalties",
  "Legal defenses and prosecution",
  "Legal defenses for animal cruelty",
  "Legal defenses for cockfighting",
  "Legal defenses for gambling prosecution",
  "Legal defenses for obscenity",
  "Legal defenses for offenses",
  "Legal defenses for online conduct",
  "Legal defenses for pen register use",
  "Legal defenses for riot",
  "Legal defenses for unmanned aircraft operation",
  "Legal defenses for weapon possession",
  "Legal defenses in prosecution",
  "Legal definitions",
  "Legal definitions and amendments",
  "Legal definitions and consent limitations",
  "Legal definitions and offenses",
  "Legal definitions in penal code",
  "Legal definitions of child and firearm",
  "Legal definitions of custody",
  "Legal definitions of exploitation",
  "Legal definitions of forgery",
  "Legal definitions of nudity and toplessness",
  "Legal definitions of vulnerable individuals",
  "Legal document types",
  "Legal documentation",
  "Legal duties and offenses",
  "Legal duties and omissions",
  "Legal effective dates",
  "Legal exceptions",
  "Legal exceptions for gifts",
  "Legal exceptions for organ donation",
  "Legal exceptions for record destruction",
  "Legal obligations",
  "Legal offense criteria",
  "Legal offenses",
  "Legal offenses involving minors",
  "Legal penalties",
  "Legal penalties and amendments",
  "Legal penalties and sentencing",
  "Legal penalties for misuse of 9-1-1",
  "Legal presumption of intent",
  "Legal presumptions in defense",
  "Legal provisions on animal treatment",
  "Legal responsibility for care",
  "Legal services exemptions",
  "Legal standards for perjury",
  "Legal statutes",
  "Legislative Acts",
  "Legislative Acts Amendments",
  "Legislative Sessions",
  "Legislative act history",
  "Legislative acts",
  "Legislative acts amendments",
  "Legislative acts and effective dates",
  "Legislative acts and statutes",
  "Legislative amendments",
  "Legislative amendments and effective dates",
  "Legislative amendments to emergency call laws",
  "Legislative amendments to insurance law",
  "Legislative and executive gifts",
  "License holder definition",
  "License holder exceptions",
  "License holder offenses",
  "Life imprisonment criteria",
  "Life imprisonment sentencing",
  "Limitations on autonomous drone force",
  "Limited liability company offenses",
  "Local Government Code Chapter 179",
  "Lottery promotion and sales",
  "Mail theft definitions",
  "Manslaughter",
  "Manufacture and distribution of decoding devices",
  "Marking of property boundaries",
  "Marriage dissolution",
  "Mass shooting",
  "Massage therapy regulations",
  "Material support or resources",
  "Materiality in insurance statements",
  "Materiality in perjury",
  "Mechanical security devices",
  "Medicaid program",
  "Medical procedure exemptions",
  "Mental health services provider definitions",
  "Mental illness and chemical dependency commitments",
  "Metal recycling regulations",
  "Military installations",
  "Minor definition",
  "Minors",
  "Misapplication of fiduciary property",
  "Misdemeanor and felony classifications",
  "Misdemeanor and felony distinctions",
  "Misdemeanor and felony offenses",
  "Misdemeanor and felony penalties",
  "Misdemeanor categories",
  "Misdemeanor classifications",
  "Misdemeanor offenses",
  "Misdemeanor penalties",
  "Misdemeanor punishments",
  "Mislabeling and adulteration",
  "Misrepresenting child as family member",
  "Mistake of law",
  "Misuse of government property",
  "Misuse of official information",
  "Money laundering",
  "Money laundering definitions",
  "Motor vehicle",
  "Motor vehicle insurance documentation",
  "Motor vehicle theft",
  "Multichannel video device offenses",
  "Multichannel video services",
  "Multiple offenses against minors",
  "Murder during felony",
  "Murder for remuneration",
  "Murder in penal institution",
  "Necessity defense",
  "Neglect and omission of care",
  "Notice requirements for bad checks",
  "Nursing home loss offenses",
  "Objectives of Code",
  "Obscene devices",
  "Obscenity definition",
  "Obscenity definitions",
  "Obscenity laws",
  "Obstructing governmental operation",
  "Obstructing passageway offense",
  "Obstruction of public passage",
  "Obstruction or retaliation offenses",
  "Occupations Code",
  "Occupations Code definitions",
  "Occupations Code licensing",
  "Ocean-going vessel gambling rules",
  "Offense Definition",
  "Offense against child",
  "Offense and Penalties",
  "Offense and misdemeanor",
  "Offense by institution superintendent",
  "Offense categorization",
  "Offense causing death",
  "Offense classification",
  "Offense classifications",
  "Offense classifications and fines",
  "Offense criteria and penalties",
  "Offense definitions",
  "Offense elements and defenses",
  "Offense grading and punishment",
  "Offense intent and conduct",
  "Offense location-based punishment",
  "Offense locations",
  "Offense prosecution",
  "Offense punishment guidelines",
  "Offense sentencing",
  "Offense-related fines",
  "Offenses against disabled individuals",
  "Offenses against property",
  "Offenses against public servants",
  "Offenses against service animals",
  "Offenses against the family",
  "Offenses and penalties for fetal tissue transactions",
  "Offenses by correctional employees",
  "Offenses involving minors and harmful material",
  "Offenses involving railroad property",
  "Offenses related to communication interception",
  "Offenses related to controlled substances",
  "Offenses related to correctional facility contraband",
  "Offenses related to providing wireless devices to inmates",
  "Official duty retaliation",
  "Official oppression by public servant",
  "Official proceeding",
  "Oil and gas equipment theft penalties",
  "Online impersonation",
  "Online promotion of prostitution",
  "Online solicitation of minors",
  "Open container in vehicle",
  "Openly carried handgun",
  "Operating aircraft while intoxicated",
  "Operating amusement ride intoxication",
  "Operating motor vehicle while intoxicated",
  "Operating or assembling amusement ride while intoxicated",
  "Operating watercraft while intoxicated",
  "Operation of unmanned aircraft",
  "Organized Criminal Activity",
  "Organized crime definitions",
  "Packers and Stockyards Act compliance",
  "Parent-child special relationship",
  "Parks and Wildlife Department employee",
  "Parole officers weapon policies",
  "Pattern of racketeering",
  "Payment demand and refusal",
  "Peace officer arrest restrictions",
  "Peace officer definitions",
  "Peace officer duties",
  "Peace officer firearm exceptions",
  "Peace officer identification",
  "Peace officer murder",
  "Peace officers weapon carry",
  "Pecuniary Loss",
  "Pecuniary Loss Classification",
  "Pecuniary gain offenses",
  "Pecuniary loss",
  "Pecuniary loss aggregation",
  "Pecuniary loss classifications",
  "Pecuniary value",
  "Pen register and trap and trace device use",
  "Penal Code",
  "Penal Code Amendments",
  "Penal Code Provisions",
  "Penal Code Section 30.06",
  "Penal Code sections",
  "Penal code",
  "Penal code amendments",
  "Penal code offenses",
  "Penal code provisions",
  "Penal code provisions on computer-generated child sexual conduct",
  "Penal code sections",
  "Penalties and classifications",
  "Penalties based on pecuniary loss",
  "Penalties for Felony Offenders",
  "Penalties for child sexual exploitation",
  "Penalties for distribution to minors",
  "Penalties for firearm accessibility offenses",
  "Penalties for fleeing",
  "Penalties for intoxicated operation",
  "Penalties for organ trade offenses",
  "Penalties for use of metal or body armor",
  "Performance and promotion",
  "Perjury",
  "Perjury and falsification definitions",
  "Perjury offenses",
  "Permitting or facilitating escape",
  "Personal protection officer duties",
  "Petroleum product definitions",
  "Petroleum product theft penalties",
  "Plea agreements in criminal cases",
  "Police service animals",
  "Political contributions",
  "Port of entry offenses",
  "Possession of alcoholic beverages in correctional facilities",
  "Possession of obscene devices",
  "Possession of tobacco products in jail",
  "Preemption Clause",
  "Premises and vehicle definitions",
  "Presumption of interference with peace officer",
  "Preventing execution of civil process",
  "Price difference thresholds",
  "Prior convictions impact",
  "Privacy expectations in changing rooms",
  "Privacy of involved persons",
  "Privacy offense penalties",
  "Privacy rights",
  "Privileged information",
  "Prize disclosure requirements",
  "Proceeds of criminal activity",
  "Production and promotion of sexual performances",
  "Professional conduct exceptions",
  "Professional licensing and certification",
  "Prohibited Relationships",
  "Prohibited camping",
  "Prohibited cockfighting activities",
  "Prohibited items in correctional facilities",
  "Prohibited sexual conduct",
  "Prohibited weapons",
  "Prohibition of cellular phones in correctional and civil commitment facilities",
  "Prohibition of sexually oriented performances",
  "Prohibition on human organ trade",
  "Prohibition on purchase and sale",
  "Prohibition on purchase and sale of human fetal tissue",
  "Promotion of obscene material",
  "Promotion of prostitution",
  "Proof of lawful immigration status",
  "Property Code exceptions",
  "Property Offenses",
  "Property custody and retrieval",
  "Property damage",
  "Property damage thresholds",
  "Property definition",
  "Property deprivation",
  "Property dispositions",
  "Property misapplication penalties",
  "Property owner notice",
  "Property recovery rights",
  "Property signage requirements",
  "Property trespass prevention",
  "Property value deduction",
  "Property value thresholds",
  "Prosecution and sentencing",
  "Prosecution conditions",
  "Prosecution defenses",
  "Prosecution jurisdiction",
  "Prosecution jurisdiction and authority",
  "Prosecution limitations",
  "Prosecution obstruction",
  "Prosecution of insurance offenses",
  "Prosecution under Alcoholic Beverage Code",
  "Prosecution under multiple laws",
  "Prosecution under multiple sections",
  "Prostitution enterprise management",
  "Prostitution involving minors",
  "Prostitution offense",
  "Prostitution offenses",
  "Prostitution proceeds",
  "Protected Mark Registration",
  "Protected areas",
  "Protected conduct",
  "Protected locations",
  "Protected property types",
  "Protection of property",
  "Protection of public servants",
  "Protective order violation",
  "Protective order violations",
  "Protective orders",
  "Providing false information to peace officer",
  "Proximity to schools",
  "Public Safety",
  "Public duty",
  "Public education reporting",
  "Public exposure to minors",
  "Public health regulations",
  "Public intoxication offense",
  "Public lewdness laws",
  "Public media definition",
  "Public officials",
  "Public place camping regulations",
  "Public place definition",
  "Public school record tampering",
  "Public servant benefits",
  "Public servant discretion",
  "Public servant gift regulations",
  "Public servant misconduct",
  "Public servant offenses",
  "Public utility interference",
  "Punishment enhancement criteria",
  "Punishment grading",
  "Punishment provisions",
  "Qualified nonprofit organization",
  "Racketeering definitions",
  "Radio communication offenses",
  "Radio communication privacy",
  "Radio frequency licensing",
  "Railroad Commission of Texas regulations",
  "Railroad property definitions",
  "Railroad signaling devices",
  "Railway Labor Act",
  "Ransomware definition",
  "Ransomware software exceptions",
  "Real property fraud",
  "Real property interest",
  "Rebuttable presumption in insurance claims",
  "Reckless Damage or Destruction",
  "Reckless driving offenses",
  "Recklessness and danger presumption",
  "Refusal of payment",
  "Refusal to comply with return order",
  "Regulations on research and disposal of fetal tissue",
  "Removal orders",
  "Rental property control",
  "Renunciation defense",
  "Repeal of legal sections",
  "Repeat felony offender penalties",
  "Repeat intoxication offenses",
  "Repeat offender sentencing",
  "Repeat offense convictions",
  "Repeat offense penalties",
  "Repeat offenses",
  "Repeated offenses",
  "Repeated telephone communications",
  "Repeated violation of court orders",
  "Reportable Conviction",
  "Reporting and investigation procedures",
  "Reporting death of institution resident",
  "Residence address",
  "Resisting arrest or search",
  "Restitution for animal injury",
  "Restraint of persons",
  "Retail Value of Counterfeit Goods",
  "Retail merchandise",
  "Retail theft detector",
  "Retail water utility service",
  "Retired law enforcement officers",
  "Retraction of false statements",
  "Revenue Code of 1986",
  "Riot definition",
  "Riot offense classification",
  "Riot offense elements",
  "Robbery definitions",
  "Robbery offense",
  "Sale and lease of video service devices",
  "Sale of harmful material to minors",
  "Sales contest regulations",
  "Sales contests",
  "Satellite receiving antennas",
  "Savings account deposits",
  "School crossing zone offenses",
  "School library",
  "School-related events",
  "Second degree felony punishment",
  "Section 22.011 and 22.021 offenses",
  "Section 25.072",
  "Secured airport area",
  "Security Officer Registration",
  "Security agreements",
  "Security interest",
  "Security officer commission",
  "Security officer firearm exceptions",
  "Security officer roles",
  "Self-defense law",
  "Senate Bills",
  "Sentencing guidelines",
  "September 1, 2023",
  "Serious bodily and mental injury",
  "Serious bodily injury",
  "Serious bodily injury to officials",
  "Service agreements",
  "Service definition",
  "Sex offender registration",
  "Sexual Assault Statute",
  "Sexual Offenses",
  "Sexual Performance by a Child",
  "Sexual abuse offenses",
  "Sexual abuse statutes",
  "Sexual assault definitions",
  "Sexual coercion",
  "Sexual conduct",
  "Sexual conduct definitions",
  "Sexual conduct offenses",
  "Sexual conduct solicitation",
  "Sexual contact and intercourse",
  "Sexual contact offenses",
  "Sexual misconduct",
  "Sexual misconduct by school employees",
  "Sexual offense convictions",
  "Sexual offenses",
  "Sexual offenses in custody",
  "Sexual offenses involving minors",
  "Sexual performance by a child",
  "Sexually explicit communication",
  "Sexually explicit media distribution",
  "Sexually explicit visual material",
  "Sexually oriented commercial activity",
  "Sexually oriented performance",
  "Sexually violent predator commitment",
  "Shelter definitions",
  "Shielding or deactivation instrument",
  "Signal encryption",
  "Silent or abusive 9-1-1 calls",
  "Simulating legal process",
  "Smuggling of persons",
  "Social networking sites",
  "Solicitation of business",
  "Solicitation of professional employment",
  "Solicitation of prostitution",
  "Spaceports",
  "Specific felony offenses and punishments",
  "Sports participant protections",
  "Spousal offense",
  "Stalking offense",
  "State Bar disciplinary rules",
  "State Jail Felony",
  "State and federal law interaction",
  "State jail felony",
  "State jail felony criteria",
  "State jail felony offense",
  "State jail felony offenses",
  "State jail felony punishment",
  "State lottery regulations",
  "State property offenses",
  "Statute Amendments",
  "Statute Text",
  "Statutory Amendments",
  "Statutory Effective Dates",
  "Statutory Law",
  "Statutory amendments",
  "Statutory effective dates",
  "Statutory history",
  "Storage and release fees",
  "Sudden passion definition",
  "Superfund site designation",
  "Taking weapon from law enforcement",
  "Tampering with consumer product",
  "Tampering with governmental records",
  "Tampering with physical evidence",
  "Tampering with railroad property",
  "Tampering with witness",
  "Tax Code cigarette stamps",
  "Telecommunication access device",
  "Telecommunication surveillance",
  "Telecommunications access device",
  "Telecommunications crimes",
  "Telecommunications device",
  "Telecommunications investigation",
  "Telecommunications service",
  "Telecommunications service provider",
  "Telecommunications service provider offenses",
  "Telephone number",
  "Temporary insanity",
  "Tenant handgun defenses",
  "Territorial Jurisdiction",
  "Terrorism definitions",
  "Testimony corroboration",
  "Texas Civil Commitment Office",
  "Texas Department of Criminal Justice",
  "Texas Department of Criminal Justice regulations",
  "Texas Department of Criminal Justice sentencing",
  "Texas Department of Insurance regulations",
  "Texas Department of Public Safety",
  "Texas Department of Transportation regulations",
  "Texas Education Agency data integrity",
  "Texas Juvenile Justice Department",
  "Texas Legislature",
  "Texas Parks and Wildlife Code",
  "Texas Penal Code",
  "Texas Penal Code Section 20A.02",
  "Texas Penal Code Section 21.11",
  "Texas Penal Code Sections 46.02 and 46.03",
  "Texas Penal Code amendments",
  "Texas Penal Code sections",
  "Texas Private Security Board",
  "Texas criminal justice sentencing",
  "Texas criminal justice system",
  "Texas criminal law",
  "Texas criminal procedure articles",
  "Texas criminal statutes",
  "Texas gambling laws",
  "Texas intoxication offense statutes",
  "Texas law enforcement policies",
  "Texas legislation",
  "Texas legislative amendments",
  "Texas penal code amendments",
  "Theft Definition",
  "Theft Offenses Consolidation",
  "Theft and stealing",
  "Theft and tampering with multichannel video services",
  "Theft by check presumption",
  "Theft conduct",
  "Theft definition",
  "Theft definitions",
  "Theft of oil and gas equipment",
  "Theft of petroleum products",
  "Theft of service",
  "Theft of trade secrets",
  "Therapeutic use defense",
  "Third degree felony punishment",
  "Threatening communication",
  "Threats and extortion",
  "Threats and harassment",
  "Threats and offensive contact",
  "Tire deflation device",
  "Tobacco and e-cigarette use",
  "Touching of students",
  "Trade secret definition",
  "Trade secret theft offenses",
  "Trademark Counterfeiting",
  "Trafficking of persons",
  "Transnational repression",
  "Transportation and lodging exceptions",
  "Transportation communications equipment",
  "Trap and trace device",
  "Trap-Neuter-Return Program",
  "Trap-Neuter-Return program",
  "Traumatic brain injury",
  "Trespass by license holder",
  "Trespass prevention",
  "Trespassing penalties",
  "Types of forged writings",
  "Unauthorized acquisition of financial information",
  "Unauthorized asset transfer",
  "Unauthorized possession",
  "Unauthorized practice of law",
  "Unauthorized recording",
  "Unauthorized tracking and monitoring",
  "Unauthorized use of telecommunications service",
  "Unauthorized use of vehicle",
  "Unborn child conduct exceptions",
  "Unborn child death exceptions",
  "Unlawful Appropriation",
  "Unlawful Weapon Transfer",
  "Unlawful access to stored communications",
  "Unlawful appropriation",
  "Unlawful carrying of weapons",
  "Unlawful custody",
  "Unlawful deep fake media",
  "Unlawful disclosure",
  "Unlawful electronic transmission",
  "Unlawful installation of tracking device",
  "Unlawful possession of body armor",
  "Unlawful possession of firearm",
  "Unlawful restraint",
  "Unlawful use of devices",
  "Unlawful use of fireworks",
  "Unlawful use of pen register",
  "Unmanned teller machine",
  "Unsolicited benefit donation",
  "Use of collision report information",
  "Use of deadly force",
  "Use of deadly weapon",
  "Use of firearms and drones",
  "Use of force",
  "Use of force against peace officer",
  "Use of force and legal defense",
  "Use of force criteria",
  "Use of force in correctional facilities",
  "Use of laser pointers",
  "Use of less-lethal force weapons",
  "Use of tire deflation device",
  "Use of vehicle or watercraft in flight",
  "Utilities Code definitions",
  "Utility definitions",
  "Utility types and classifications",
  "Utility worker protections",
  "Value determination",
  "Value of insurance claims",
  "Value of telecommunications service",
  "Value thresholds for offenses",
  "Value-based offense classification",
  "Value-based offense grading",
  "Vehicle definition",
  "Vehicle possession transfer",
  "Vehicle-related offenses",
  "Veterinarian definition",
  "Victim Age",
  "Victim Protection and Charges",
  "Victim age categories",
  "Victim protection",
  "Victim relationship",
  "Victim-related charge limitations",
  "Violation of court orders",
  "Violation of protective orders",
  "Violent crimes",
  "Visual Material",
  "Visual image transmission",
  "Volunteer emergency services personnel",
  "Voyeurism offense",
  "Weapon offense classifications",
  "Weapons definitions",
  "Wholesale distributor of prescription drugs",
  "Written communication requirements",
  "Youth service centers",
  "Zip gun definition",
  "abduction agreements",
  "abuse of official capacity",
  "academic product definition",
  "academic product preparation offense",
  "access software provider",
  "accountant-client confidentiality",
  "acquisition of property interest",
  "admission of unadjudicated offense",
  "admitted offenses",
  "adopted child definition",
  "adoption regulations",
  "advertising for child placement",
  "affirmative defense",
  "affirmative defense criteria",
  "affirmative defense in prosecution",
  "affirmative defense to gambling prosecution",
  "affirmative defenses",
  "affirmative defenses in sexual abuse cases",
  "age determination methods",
  "age of victim",
  "age-related offense definitions",
  "age-related prosecution limits",
  "aggravating factors in sexual crimes",
  "aggravating factors in smuggling",
  "aggregate amount thresholds",
  "aiding terrorism",
  "altered gambling equipment",
  "ammunition types",
  "amusement devices",
  "animal abandonment",
  "animal abuse",
  "animal control and code enforcement officers",
  "animal control authority",
  "animal cruelty offenses",
  "animal husbandry practices",
  "animal injury and killing defenses",
  "animal neglect",
  "animal transportation abuse",
  "appeal procedures",
  "armed forces and security personnel",
  "armor-piercing ammunition",
  "arrest and search",
  "artificial intelligence application",
  "artificial intelligence depictions",
  "artificial intelligence generated images",
  "artificially generated media",
  "assault on public servants",
  "attorney general assistance",
  "attorney general jurisdiction",
  "attorney general powers",
  "attorney involvement",
  "authorization for airport access",
  "authorized vendor liability",
  "benefit solicitation",
  "benefit solicitation offenses",
  "betting regulations",
  "bigamy laws",
  "bodily injury",
  "bodily injury or death",
  "bona fide contests",
  "bookmaking",
  "burden of proof",
  "burglary of vehicles",
  "burglary offenses",
  "business entity offenses",
  "camping prohibition regulations",
  "capital felony",
  "capital felony prosecution",
  "card revocation notice",
  "caregiver legal responsibilities",
  "cargo theft",
  "cargo theft offenses",
  "carrying handgun while intoxicated",
  "catalytic converter possession laws",
  "catalytic converter theft",
  "causation in criminal law",
  "cemetery regulations",
  "certificate of authority and title requirements",
  "check issuance",
  "chemical and explosive devices",
  "chemical dependency",
  "chemical dispensing device",
  "child abandonment",
  "child conduct law",
  "child custody and guardianship",
  "child custody offenses",
  "child custody violations",
  "child depiction laws",
  "child exploitation",
  "child exploitation offenses",
  "child grooming offense",
  "child labor laws",
  "child mental illness",
  "child placement exceptions",
  "child pornography depiction",
  "child pornography laws",
  "child sexual abuse",
  "child sexual abuse material",
  "child sexual conduct offenses",
  "child sexual exploitation",
  "child sexual offense",
  "child smuggling offense",
  "child-like sex doll promotion",
  "child-placing agency standards",
  "cigarette restrictions",
  "civil commitment facility offenses",
  "civil commitment facility services",
  "civil liability protection",
  "civil rights violations",
  "class C misdemeanor",
  "classification of offenses",
  "code reference conventions",
  "coercion and force",
  "coercion definitions",
  "coercion of public servant",
  "cohabitation and marriage",
  "coin-operated machine offenses",
  "commercial shipment regulations",
  "communicating gambling information",
  "communication carrier protections",
  "communication common carrier",
  "community corrections facility offenses",
  "community supervision discharge",
  "compelling prostitution",
  "complaint and legal action procedures",
  "complaint dismissal procedure",
  "complicity",
  "components of explosives",
  "compulsion defense",
  "computation of age",
  "computer crime",
  "computer crime defenses",
  "computer fraud",
  "computer property definition",
  "computer security breach",
  "computer security offenses",
  "computer-generated child depictions",
  "computer-generated child sexual conduct",
  "computer-generated child sexual images",
  "computer-related election offenses",
  "concurrent and consecutive sentences",
  "concurrent jurisdiction",
  "concurrent sentences",
  "condominium ownership rights",
  "condominium property",
  "conduct of another",
  "confidential certification",
  "confinement",
  "conflict of law",
  "consecutive sentences",
  "consent for interception",
  "consolidation of prosecutions",
  "conspiracy liability",
  "construction of penal code",
  "contingent fee contracts",
  "continuous sexual abuse",
  "contraband definition",
  "contraband in correctional facility",
  "contraband introduction",
  "contracts of indemnity",
  "controlled substance exposure",
  "controlled substance violations",
  "conviction and penalty enhancement rules",
  "conviction enhancement",
  "conviction similarity",
  "copper or brass theft",
  "corporate liability",
  "correctional and detention facilities",
  "correctional facilities",
  "correctional facility",
  "correctional facility offenses",
  "correctional facility regulations",
  "correctional facility security",
  "counterfeit credit and debit cards",
  "counterfeit gift cards",
  "counterfeit telecommunications device",
  "counterfeiting offenses",
  "court custody orders",
  "court discretion on sentencing",
  "court fines and penalties",
  "court jurisdiction",
  "court order violation",
  "court orders and compliance",
  "court orders for information gathering",
  "court-ordered restitution",
  "credit and property fraud",
  "credit card data theft",
  "credit card definitions",
  "credit card fraud",
  "credit card fraud offenses",
  "credit card transaction laundering",
  "credit transaction records",
  "criminal activity exceptions",
  "criminal attempt",
  "criminal charges",
  "criminal classification",
  "criminal classifications",
  "criminal combination criteria",
  "criminal conspiracy",
  "criminal episode definition",
  "criminal homicide definitions",
  "criminal intent",
  "criminal law procedures",
  "criminal mischief",
  "criminal negligence",
  "criminal negligence offenses",
  "criminal objective",
  "criminal offense categories",
  "criminal offense classification",
  "criminal offense classifications",
  "criminal offense definitions",
  "criminal offense knowledge",
  "criminal offenses",
  "criminal offenses and defenses",
  "criminal penalties",
  "criminal penalties for document fraud",
  "criminal penalties for fraud",
  "criminal penalties for gift card offenses",
  "criminal penalties for offenses",
  "criminal penalties for recruitment",
  "criminal penalties for solicitation",
  "criminal procedure amendments",
  "criminal proceeds",
  "criminal prosecution",
  "criminal prosecution for bad checks",
  "criminal prosecution limitations",
  "criminal responsibility",
  "criminal responsibility age",
  "criminal responsibility defenses",
  "criminal responsibility justification",
  "criminal responsibility principles",
  "criminal simulation",
  "criminal street gang membership",
  "criminal street gang offenses",
  "criminal street gangs",
  "criminal threats and violence",
  "criminal trespass",
  "criminal value thresholds",
  "critical infrastructure",
  "critical infrastructure damage",
  "critical infrastructure facility",
  "culpability requirement",
  "culpable mental states",
  "custody transfer offenses",
  "cybercrime penalties",
  "damage repair costs",
  "dangerous wild animal",
  "data theft",
  "deadly force justification",
  "deadly force limitations",
  "deadly weapon in penal institution",
  "deadly weapon use",
  "debit card misuse",
  "debit card violations",
  "deceptive academic product marketing",
  "decryption of privileged information",
  "deduction of legal interest in stolen property",
  "deep fake media",
  "deep fake media consent",
  "defendant capacity",
  "defendant rights",
  "defense in substance offenses",
  "defense limitations",
  "defense of third person",
  "defense to firearm prosecution",
  "defense to prosecution",
  "defenses to academic misconduct",
  "defenses to custody interference",
  "defenses to prosecution",
  "deferred adjudication",
  "deferred adjudication community supervision",
  "deferred adjudication impact",
  "definition of correctional facility",
  "definition of identifying information",
  "definitions of livestock terms",
  "definitions of writing",
  "demand for payment notice",
  "destruction of copper or brass components",
  "detention facility",
  "detention facility offenses",
  "determining property or service value",
  "device installation requirements",
  "digital deception",
  "digital gift card information",
  "digital imprint fraud",
  "disabled individual",
  "disabled individual safety",
  "disaster area offenses",
  "discharge of firearm",
  "disrupting meetings",
  "driving while intoxicated",
  "drug offenses",
  "due diligence defense",
  "education code",
  "effective dates",
  "elderly and disabled abandonment",
  "elderly and disabled victims",
  "elderly individual protection",
  "elderly individual protections",
  "elderly victim protection",
  "electrical power facilities",
  "electronic access interference",
  "electronic communication privacy",
  "emergency evacuation order",
  "emergency evacuation orders",
  "emergency infant care",
  "emergency medical care",
  "emergency report offenses",
  "emergency services",
  "emergency services personnel",
  "emergency shelter during disaster",
  "emergency shelter firearm rules",
  "employment agency duties",
  "employment and service fraud",
  "employment restrictions for firearm possession",
  "enforcement of federal firearm laws",
  "enhanced penalties for vulnerable victims",
  "enterprise control",
  "entrapment",
  "entry and notice definitions",
  "equipment and communication wires",
  "evidence admissibility",
  "evidence tampering",
  "exceptional sentences",
  "exceptions for lawful conduct",
  "exceptions to child sale prohibition",
  "exceptions to offenses",
  "exceptions to prosecution",
  "explosive weapon definition",
  "facility impairment or interruption",
  "false alarm laws",
  "false caller identification",
  "false claims",
  "false statement offenses",
  "false statements",
  "false statements in health care",
  "family and dating relationships",
  "family relationship defense",
  "family violence",
  "family violence exceptions",
  "family violence provisions",
  "fear and intimidation",
  "felony and misdemeanor classifications",
  "felony categorization",
  "felony classification",
  "felony classification by pecuniary gain",
  "felony classification by property value",
  "felony classification for voting offenses",
  "felony classifications",
  "felony convictions",
  "felony degree enhancements",
  "felony degrees",
  "felony offense convictions",
  "felony offenses",
  "felony penalties",
  "felony punishment",
  "felony sentencing",
  "felony theft thresholds",
  "fiduciary offenses",
  "financial abuse",
  "financial abuse of elderly",
  "financial information storage",
  "financial institution liability",
  "financing criminal activity",
  "fire exit alarm deactivation",
  "firearm confiscation program",
  "firearm definitions",
  "firearm discharge regulations",
  "firearm possession",
  "firearm possession defenses",
  "firearm possession exemptions",
  "firearm possession legal defenses",
  "firearm possession offenses",
  "firearm possession on property",
  "firearm possession regulations",
  "firearm possession restrictions",
  "firearm prohibition signage",
  "firearm regulations",
  "firearm sale requirements",
  "firearm transfer regulations",
  "firearms and weapons offenses",
  "fireworks definitions",
  "first responder certification",
  "first responder firearm exemptions",
  "first responder handgun carry",
  "foreign government agents",
  "fraud and harm",
  "fraud definitions",
  "fraudulent benefit",
  "fraudulent claims thresholds",
  "fraudulent degree",
  "fraudulent destruction of writing",
  "fraudulent document execution",
  "fraudulent health care claims",
  "fraudulent lien claims",
  "fraudulent lien or claim",
  "fraudulent military record use",
  "fraudulent use of cards",
  "fraudulent use of identification",
  "fraudulent use of identifying information",
  "funeral service disruptions",
  "funeral service regulations",
  "gambling device",
  "gambling offense classifications",
  "gambling offenses",
  "gambling paraphernalia",
  "gambling place",
  "gang-free zones",
  "gang-free zones mapping",
  "gas processing plant",
  "gift card fraud",
  "global positioning monitoring system tampering",
  "government record fraud",
  "government service contracts",
  "governmental meeting locations",
  "governmental record offenses",
  "handgun carry defense",
  "handgun carry restrictions",
  "handgun display regulations",
  "handgun license exceptions",
  "handgun possession",
  "handgun possession defenses",
  "handgun possession during disaster",
  "handgun possession restrictions",
  "handgun visibility",
  "handler control violations",
  "health and safety code violations",
  "health care fraud",
  "health care fraud offenses",
  "health care fraud penalties",
  "health care program fraud",
  "health care program participation",
  "health care provider definitions",
  "health care provider misconduct",
  "high hazard dam",
  "hindering official proceedings",
  "hindering prosecution",
  "historical reenactment regulations",
  "hoax bomb definition",
  "holster",
  "hospital personnel",
  "hotel firearm policies",
  "hotel guest defenses",
  "hotel guest handgun regulations",
  "human corpse concealment",
  "human smuggling offenses",
  "human trafficking",
  "human trafficking prevention services",
  "identifiable child definition",
  "identification number definition",
  "ignition interlock device",
  "illegal recruitment of athletes",
  "illuminating aircraft with laser",
  "imprisonment terms",
  "improper educator-student relationship",
  "in loco parentis definition",
  "incapacity to consent",
  "informant definition",
  "injury and killing of police animals",
  "insanity defense",
  "institution of higher education",
  "insufficient funds",
  "insufficient funds check offense",
  "insurance claim aggregation",
  "insurance claims",
  "insurance fraud",
  "insurance fraud definitions",
  "insurance fraud prosecution",
  "intellectual property registration",
  "intent to cause fear or disruption",
  "intent to defraud",
  "intent to defraud or harm",
  "intent to deprive merchant",
  "intent to facilitate crime",
  "intentional conduct",
  "interception device defense",
  "interception device use",
  "interception devices",
  "interception of communications",
  "intercollegiate athletics regulations",
  "interference with child custody",
  "interference with public duties",
  "internet service provider liability",
  "intimate visual material",
  "intoxicated driving offenses",
  "intoxication and consent",
  "joinder of offenses",
  "judicial and administrative corruption",
  "judicial officers",
  "jugging offense",
  "jurisdiction based on death",
  "jury instructions",
  "jury unanimity",
  "jury unanimity requirements",
  "justifiable force",
  "justification for deadly force",
  "justification for force",
  "juvenile adjudication as felony",
  "juvenile court jurisdiction",
  "juvenile offense exceptions",
  "knife regulations",
  "laser pointer offenses",
  "law enforcement",
  "law enforcement access",
  "law enforcement agents",
  "law enforcement authorization",
  "law enforcement communications",
  "law enforcement deception defenses",
  "law enforcement defense",
  "law enforcement duties",
  "law enforcement insignia",
  "law enforcement inspection",
  "law enforcement interception",
  "law enforcement officer definition",
  "law enforcement officers",
  "law enforcement orders",
  "law enforcement pension",
  "law enforcement procedures",
  "law enforcement tactics",
  "lawful arrest",
  "lawful criminal investigation",
  "lawful hunting and agriculture practices",
  "lawful interception conditions",
  "leasing personal property",
  "legal advice restrictions",
  "legal amendments",
  "legal amendments and effective dates",
  "legal amendments and statutes",
  "legal amendments to gambling laws",
  "legal consequences",
  "legal defenses",
  "legal defenses and exceptions",
  "legal defenses for license holders",
  "legal defenses in bigamy",
  "legal defenses in prosecution",
  "legal defenses in telecommunications offenses",
  "legal definitions",
  "legal definitions in election code",
  "legal definitions in family violence context",
  "legal definitions of assault",
  "legal definitions of consent",
  "legal definitions of entry",
  "legal definitions of human corpse",
  "legal definitions of laser pointer",
  "legal definitions of offenses",
  "legal duty to protect property",
  "legal exceptions",
  "legal exemptions",
  "legal expenses recovery",
  "legal interest deduction",
  "legal justification for force",
  "legal justification for non-deadly force",
  "legal offenses",
  "legal penalties",
  "legal penalties for animal harm",
  "legal penalties for deep fakes",
  "legal penalties for visual material",
  "legal presumption",
  "legal presumptions in gift card crimes",
  "legal presumptions of knowledge",
  "legal presumptions of notice",
  "legal procedures",
  "legal process simulation",
  "legal prosecution guidelines",
  "legal prosecution standards",
  "legal restitution",
  "legal solicitation restrictions",
  "legal standards for force",
  "legal statutes",
  "legal statutes and penalties",
  "legislative amendments",
  "legislative and executive misconduct",
  "lesser included offense",
  "license holder",
  "license holder offenses",
  "license plate removal and inventory",
  "licensed child-placing agencies",
  "licensed handgun carriers",
  "licensing violations",
  "livestock animal cruelty",
  "local government employment",
  "location-restricted knife offenses",
  "lottery definitions",
  "machine gun description",
  "mail appropriation offense",
  "mail appropriation offenses",
  "managed care organization violations",
  "manufactured home handgun rules",
  "manufactured home regulations",
  "maps as evidence",
  "marriage eligibility",
  "mental disease or defect",
  "mental state proof requirements",
  "metering device interference",
  "methods of sending notice",
  "military record misrepresentation",
  "minimum imprisonment terms",
  "minor definition",
  "minor depiction laws",
  "misdemeanor and felony classifications",
  "misdemeanor and felony degrees",
  "misdemeanor and felony grading",
  "misdemeanor and felony offenses",
  "misdemeanor and felony penalties",
  "misdemeanor classification",
  "misdemeanor classifications",
  "misdemeanor classifications and penalties",
  "misdemeanor offender penalties",
  "misdemeanor offense",
  "misdemeanor offenses",
  "misdemeanor penalties",
  "misdemeanor punishment",
  "misleading information",
  "misleading legal claims",
  "misrepresentation in health care",
  "misrepresentation of law enforcement property",
  "mistake of fact defense",
  "misuse of false records",
  "misuse of government property",
  "mitigation of punishment",
  "monetary benefit valuation",
  "mortgage loan appraisal fraud",
  "mortgage loan offense investigation",
  "motor vehicle",
  "motor vehicle and watercraft",
  "motor vehicle dismantling records",
  "motor vehicle felony classification",
  "motor vehicle offenses",
  "motor vehicle salvage rules",
  "multiple prosecutions",
  "municipal engineer responsibilities",
  "municipal ordinances",
  "murder of minors",
  "murder statute",
  "natural gas facilities",
  "negotiable instruments",
  "negotiable instruments theft",
  "new trial procedures",
  "noise from space flight activities",
  "non-consensual disclosure",
  "non-consensual penetration",
  "non-consensual sexual acts",
  "nonconsensual interception",
  "noncustodial parent offenses",
  "notice demanding return",
  "notice requirements",
  "notice requirements for weapons",
  "obscene material offenses",
  "obstruction of interception",
  "obstruction of investigation",
  "offense against public servant",
  "offense charges",
  "offense classification",
  "offense classification by retail value",
  "offense classification by value",
  "offense classifications",
  "offense conduct",
  "offense definitions",
  "offense location and jurisdiction",
  "offense location-based punishment enhancement",
  "offense of soliciting confidential information",
  "offense punishment enhancements",
  "offense sentencing enhancements",
  "offense severity",
  "offense severity enhancements",
  "offenses against elderly individuals",
  "official duties exemptions",
  "official duty retaliation",
  "oil and gas facilities",
  "online promotion offenses",
  "open container offense",
  "organized criminal activity",
  "organized retail theft",
  "parties to offenses",
  "payment and return obligations",
  "payment card data transfer",
  "payment refusal",
  "peace officer authority",
  "peace officer citation procedures",
  "peace officer device installation",
  "peace officer exceptions",
  "peace officer protection",
  "peaceful assembly",
  "pecuniary loss",
  "pecuniary loss thresholds",
  "penal code",
  "penal code amendments",
  "penal code amendments and effective dates",
  "penal code penalties",
  "penal code provisions",
  "penalties and classifications",
  "penalties for bias-motivated offenses",
  "penalties for bigamy",
  "penalties for card-related crimes",
  "penalties for counterfeiting",
  "penalties for drone violations",
  "penalties for laser misuse",
  "penalties for smoking",
  "penalties for smuggling",
  "penalty enhancement",
  "penalty for retaliation",
  "personal injury communication",
  "personal property preservation",
  "personnel and transportation assets",
  "pesticide transaction documentation",
  "picketing restrictions",
  "plea agreement",
  "plea agreements",
  "police service animal offenses",
  "political contributions exception",
  "possession after conviction",
  "possession and use offenses",
  "possession of child pornography",
  "possession of child-like sex dolls",
  "possession of gambling devices",
  "possession of lewd visual material",
  "possession of stolen gift card information",
  "possession offenses",
  "postal service mail security",
  "postsecondary degree",
  "postsecondary educational institution",
  "pregnant individuals",
  "premises types",
  "preparatory offense",
  "preparatory offenses",
  "presumption in criminal law",
  "presumption of incapacity under age 15",
  "prevention of escape",
  "previous conviction impact",
  "prior convictions",
  "prior convictions impact",
  "privacy protections for public servants",
  "privacy violations",
  "private investigator authorization",
  "private place definition",
  "proceeds accounting requirements",
  "process server duties",
  "prohibited firearm possession",
  "prohibited locations",
  "prohibited weapons",
  "prohibition measures",
  "prohibition on disclosure of non-public information",
  "promotion of obscene visual material",
  "property and service fraud",
  "property code regulations",
  "property damage",
  "property damage offenses",
  "property disposition rules",
  "property entry regulations",
  "property firearm prohibition notices",
  "property interest defense",
  "property price manipulation",
  "property theft classifications",
  "property types in theft",
  "property use for crimes",
  "property value assessment",
  "property value classification",
  "property value thresholds",
  "prosecuting attorney authorization",
  "prosecuting attorney obligations",
  "prosecution conditions",
  "prosecution cooperation",
  "prosecution coordination",
  "prosecution defense conditions",
  "prosecution defenses",
  "prosecution defenses excluded",
  "prosecution for trafficking",
  "prosecution guidelines",
  "prosecution guidelines for laser incidents",
  "prosecution jurisdiction",
  "prosecution of computer crimes",
  "prosecution provisions",
  "prosecution under multiple laws",
  "prostitution crimes",
  "prostitution definitions",
  "prostitution law",
  "prostitution offense",
  "prostitution offenses",
  "prostitution promotion",
  "protection of life or health",
  "protection of persons",
  "protection of third person's property",
  "protective orders",
  "provider management roles",
  "proximity to protected locations",
  "public highway regulations",
  "public indecency laws",
  "public nuisance noise",
  "public place offenses",
  "public places",
  "public safety regulations",
  "public security officers",
  "public servant document filing",
  "public servant information access",
  "public servant misconduct",
  "public servant offenses",
  "public servant protection",
  "public servant status",
  "public servant theft",
  "public utility tampering",
  "punishment enhancement",
  "punishment for repeat offenses",
  "punishment stage",
  "racketeering offenses",
  "radio communication regulations",
  "railroad switching yard access",
  "railway labor act defense",
  "reasonable medical care",
  "rebuttable presumptions",
  "reckless driving exhibition",
  "reckless injury",
  "recklessness",
  "record alteration",
  "recordkeeping requirements",
  "refusal to release fraudulent lien",
  "regulatory agency misconduct",
  "regulatory commissions",
  "rental agreement",
  "rental agreement terms",
  "renunciation defense",
  "repeat felony convictions",
  "repeat offender penalties",
  "repeat offense convictions",
  "repeat offense penalties",
  "repeat offenses",
  "reserve law enforcement officer",
  "resisting arrest",
  "restitution for damages",
  "restitution for victims",
  "restitution procedures",
  "restricted premises",
  "restricted-use pesticide definitions",
  "restricted-use pesticide purchase regulations",
  "retail theft detection prevention",
  "retail theft instruments",
  "retail theft prosecution",
  "retaliation against public servants",
  "retaliation murders",
  "retreat requirement",
  "rigging publicly exhibited contests",
  "right to severance",
  "robbery offenses",
  "sale or purchase of child",
  "satellite receiving antennas",
  "school and postsecondary institution policies",
  "school premises",
  "school-related offenses",
  "scientific research exemption",
  "screening checkpoint procedures",
  "secured property disposition",
  "security interest defense",
  "security officer authorization",
  "security officer duties",
  "security officer identification",
  "security officer training",
  "self-defense law",
  "seller description requirements",
  "sentencing for multiple offenses",
  "sentencing hearing procedures",
  "sentencing rules",
  "serious bodily injury",
  "service payment obligations",
  "service theft classification",
  "sex offender registration",
  "sexual abuse offenses",
  "sexual activity crimes",
  "sexual assault of a child",
  "sexual assault offenses",
  "sexual assault victimization",
  "sexual harassment",
  "sexual offenses",
  "sexual offenses in schools",
  "sexually violent offense definition",
  "sexually violent predator commitment",
  "simulating document offenses",
  "smoking prohibition",
  "smoking regulations",
  "soliciting benefits",
  "speech and expression defense",
  "sporting event reports",
  "stash house operation",
  "state and family code references",
  "state funding restrictions",
  "state government position fraud",
  "state jail felony",
  "state jail felony and misdemeanor classifications",
  "state jail felony classifications",
  "state jail felony criteria",
  "state jail felony enhancement",
  "state jail felony penalties",
  "state jail felony reduction",
  "state jail felony theft",
  "state law enforcement agencies",
  "state lottery participation",
  "state of disaster declarations",
  "state of disaster evacuation",
  "statutory amendments",
  "statutory amendments and effective dates",
  "stealing or receiving stolen checks",
  "steelmaking facility",
  "stolen card possession",
  "stolen property presumption",
  "stolen vehicle reporting",
  "substandard degree",
  "super-intensive supervision program",
  "tactical medical professional",
  "tampering with electronic monitoring device",
  "tampering with electronic voting machines",
  "tampering with identification numbers",
  "telecommunications access device fraud",
  "telecommunications access device publication",
  "telecommunications facilities",
  "telecommunications fraud",
  "telecommunications service theft",
  "tenant firearm rights",
  "tenant handgun rights",
  "tenant rights",
  "terrorism offenses",
  "terroristic threat offense",
  "testimonial immunity",
  "theft aggregation",
  "theft involving controlled substances",
  "theft misdemeanor categories",
  "theft of controlled substance",
  "theft offense statutes",
  "theft value classification",
  "theft value thresholds",
  "threatening behavior",
  "threats",
  "threats for benefit",
  "tire deflation device",
  "tracking and monitoring without consent",
  "tracking device removal by health care provider",
  "trafficked child",
  "transmission facility",
  "transportation communications equipment",
  "treatment based on religious healing",
  "trial severance",
  "unactivated gift cards",
  "unauthorized absence from correctional facility",
  "unauthorized card use",
  "unauthorized computer access",
  "unauthorized enforcement of foreign law",
  "unauthorized legal contact",
  "unauthorized payments",
  "unauthorized practice of law",
  "unborn child injury exceptions",
  "unlawful debt",
  "unlawful debt collection",
  "unlawful mail receptacle key conduct",
  "unlawful telecommunications device",
  "unmanned aircraft operation",
  "unmanned aircraft regulations",
  "unregulated custody transfer",
  "use of deadly force",
  "use of devices to protect property",
  "use of force",
  "use of force by educators",
  "use of force by guardians",
  "use of force justification",
  "use of force to protect property",
  "use of prior convictions",
  "use of proceeds from racketeering",
  "used goods business regulations",
  "used motor vehicle purchase reporting",
  "utility providers",
  "valuation of stolen retail merchandise",
  "value of documents in theft cases",
  "value-based offense thresholds",
  "vandalism of human remains",
  "vehicle location disclosure",
  "veterinarian negligence defense",
  "violent crimes",
  "virtual meeting disturbances",
  "visual material definitions",
  "visual material promotion",
  "voluntary act or omission",
  "voluntary renunciation",
  "volunteer emergency personnel defense",
  "voter influence offenses",
  "vulnerable victims",
  "water treatment facilities",
  "watercraft definition",
  "weapon carrying regulations",
  "weapon possession restrictions",
  "weapon theft from officer",
  "weapon training",
  "weapon-free school zone penalty",
  "weapon-free zones",
  "wildlife laws and regulations",
  "wire communication interception",
  "wiring material classifications",
  "written notice requirements",
  "youth and educational institutions",
];

interface ChatInterfaceProps {
  apiKey: string;
  onApiKeyReset: () => void;
}

export default function ChatInterface({
  apiKey,
  onApiKeyReset,
}: ChatInterfaceProps) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [userMessage, setUserMessage] = useState("");
  const [model, setModel] = useState("gpt-4.1-mini");
  const [isLoading, setIsLoading] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [isPdfUploaded, setIsPdfUploaded] = useState(false);
  const [selectedTopic, setSelectedTopic] = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!userMessage.trim() || isLoading || !isPdfUploaded) return;

    const newUserMessage: Message = {
      id: Date.now().toString(),
      role: "user",
      content: userMessage,
      timestamp: new Date(),
    };

    setMessages((prev) => [...prev, newUserMessage]);
    setUserMessage("");
    setIsLoading(true);

    // Create assistant message with streaming content
    const assistantMessage: Message = {
      id: (Date.now() + 1).toString(),
      role: "assistant",
      content: "",
      timestamp: new Date(),
      isStreaming: true,
    };

    setMessages((prev) => [...prev, assistantMessage]);

    try {
      const response = await fetch(
        `${
          process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"
        }/api/chat`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            user_message: userMessage,
            model,
            api_key: apiKey,
          }),
        }
      );

      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`);
      }

      if (!response.body) {
        throw new Error("No response body");
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();

      while (true) {
        const { done, value } = await reader.read();

        if (done) break;

        const chunk = decoder.decode(value);

        setMessages((prev) =>
          prev.map((msg) =>
            msg.id === assistantMessage.id
              ? { ...msg, content: msg.content + chunk }
              : msg
          )
        );
      }

      // Mark streaming as complete
      setMessages((prev) =>
        prev.map((msg) =>
          msg.id === assistantMessage.id ? { ...msg, isStreaming: false } : msg
        )
      );
    } catch (error) {
      console.error("Chat error:", error);
      setMessages((prev) =>
        prev.map((msg) =>
          msg.id === assistantMessage.id
            ? {
                ...msg,
                content:
                  "Sorry, there was an error processing your request. Please try again.",
                isStreaming: false,
                isError: true,
              }
            : msg
        )
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSubmit(e as any);
    }
  };

  const handleTextareaResize = () => {
    if (textareaRef.current) {
      textareaRef.current.style.height = "auto";
      textareaRef.current.style.height =
        Math.min(textareaRef.current.scrollHeight, 120) + "px";
    }
  };

  return (
    <div className="flex flex-col h-full bg-white dark:bg-gray-800 rounded-lg shadow-lg border border-border overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-border bg-card">
        <div className="flex items-center space-x-3">
          <div className="w-8 h-8 bg-gradient-to-br from-blue-500 to-purple-600 rounded-lg flex items-center justify-center">
            <MessageSquare className="w-4 h-4 text-white" />
          </div>
          <div>
            <h2 className="font-semibold">AI Assistant</h2>
            <p className="text-xs text-muted-foreground">{model}</p>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={() => setShowSettings(!showSettings)}
            className="p-2 hover:bg-accent rounded-md transition-colors"
            title="Settings"
          >
            <Settings className="w-4 h-4" />
          </button>
          <button
            onClick={onApiKeyReset}
            className="text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            Change API Key
          </button>
        </div>
      </div>

      {/* Settings Panel */}
      {showSettings && (
        <div className="p-4 bg-muted border-b border-border space-y-4 animate-slide-up">
          <div>
            <label className="block text-sm font-medium mb-2">Model</label>
            <select
              value={model}
              onChange={(e) => setModel(e.target.value)}
              className="w-full px-3 py-2 border border-input rounded-md bg-background focus:ring-2 focus:ring-ring focus:border-transparent"
            >
              <option value="gpt-4.1-mini">GPT-4.1-mini</option>
              <option value="gpt-4">GPT-4</option>
              <option value="gpt-3.5-turbo">GPT-3.5-turbo</option>
            </select>
          </div>
        </div>
      )}

      {/* Quick Actions: Upload + Topic Search */}
      <div className="sticky top-0 z-10 p-4 bg-gradient-to-b from-background to-muted/40 border-b border-border backdrop-blur supports-[backdrop-filter]:bg-background/70">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <PDFUpload
            apiKey={apiKey}
            onUploadSuccess={() => setIsPdfUploaded(true)}
          />

          <TopicSelector
            topics={topics}
            selectedTopic={selectedTopic}
            onSelect={setSelectedTopic}
          />
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.length === 0 ? (
          <div className="flex items-center justify-center h-full">
            <div className="text-center text-muted-foreground">
              <Bot className="w-16 h-16 mx-auto mb-4 opacity-50" />
              <h3 className="text-lg font-medium mb-2">
                Upload a PDF to start
              </h3>
              <p className="text-sm">
                {isPdfUploaded
                  ? "PDF uploaded! Choose a topic and start asking questions."
                  : "Use the upload box above, then select a topic and ask away."}
              </p>
            </div>
          </div>
        ) : (
          <>
            {messages.map((message) => (
              <MessageBubble key={message.id} message={message} />
            ))}
            <div ref={messagesEndRef} />
          </>
        )}
      </div>

      {/* Input Form */}
      <form onSubmit={handleSubmit} className="p-4 border-t border-border">
        <div className="flex space-x-2">
          <div className="flex-1 relative">
            <textarea
              ref={textareaRef}
              value={userMessage}
              onChange={(e) => {
                setUserMessage(e.target.value);
                handleTextareaResize();
              }}
              onKeyDown={handleKeyDown}
              placeholder="Type your message... (Shift+Enter for new line)"
              disabled={isLoading}
              rows={1}
              className="w-full px-4 py-3 pr-12 border border-input rounded-lg bg-background focus:ring-2 focus:ring-ring focus:border-transparent outline-none resize-none transition-colors"
              style={{ minHeight: "48px", maxHeight: "120px" }}
            />
          </div>

          <button
            type="submit"
            disabled={!userMessage.trim() || isLoading}
            className="px-4 py-3 bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed rounded-lg font-medium transition-colors flex items-center space-x-2"
          >
            <Send className="w-4 h-4" />
          </button>
        </div>

        <div className="flex items-center justify-between mt-2 text-xs text-muted-foreground">
          <span>Press Enter to send, Shift+Enter for new line</span>
          {isLoading && (
            <div className="flex items-center space-x-2">
              <div className="typing-indicator"></div>
              <span>AI is typing...</span>
            </div>
          )}
        </div>
      </form>
    </div>
  );
}
